const blogPosts = [
  {
    id: 1,
    title: "The Art of JavaScript",
    author: "John Doe",
    date: "2024-05-12",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    tags: "Programming, JS",
  },
  {
    id: 2,
    title: "React Hooks Tutorial",
    author: "Jane Smith",
    date: "2024-05-10",
    content: "Suspendisse potenti. Nam in metus eu magna commodo...",
    tags: "Frontend Development, React, Hook",
  },
  {
    id: 3,
    title: "Introduction to Node.js",
    author: "Chris Johnson",
    date: "2024-05-08",
    content: "Quisque sit amet lobortis nunc. Sed fermentum, ex nec...",
    tags: "Backend Development, Node",
  },
  {
    id: 4,
    title: "CSS Best Practices",
    author: "Emily Brown",
    date: "2024-05-05",
    content: "Fusce vitae dapibus leo. Integer nec neque id odio...",
    tags: "Web Development, CSS",
  },
  {
    id: 5,
    title: "Getting Started with Python",
    author: "Michael Clark",
    date: "2024-05-03",
    content: "Vestibulum in mattis mauris. Proin auctor lorem...",
    tags: "Programming, Python",
  },
  {
    id: 6,
    title: "UI Design Principles",
    author: "Sarah Johnson",
    date: "2024-04-30",
    content: "Donec aliquet velit nec sapien fermentum...",
    tags: "Design, UI, UX",
  },
  {
    id: 7,
    title: "Data Structures in Java",
    author: "Alex Lee",
    date: "2024-04-28",
    content: "Pellentesque habitant morbi tristique senectus...",
    tags: "Programming, Java, DSA",
  },
  {
    id: 8,
    title: "Introduction to SQL",
    author: "Jessica White",
    date: "2024-04-25",
    content: "Curabitur at elementum ex. Integer interdum, mi eu...",
    tags: "Databases, SQL",
  },
  {
    id: 9,
    title: "Responsive Web Design",
    author: "David Smith",
    date: "2024-04-22",
    content: "In et metus non elit mollis tempor...",
    tags: "Web Development, Frontend, Responsiveness",
  },
  {
    id: 10,
    title: "JavaScript Frameworks Comparison",
    author: "Laura Anderson",
    date: "2024-04-20",
    content: "Sed nec est nunc. Nulla fringilla lacinia urna...",
    tags: "Programming, JS",
  },
];

export default blogPosts;
